### ISSUE TITLE
Sports DVR recordings metadata lost after encode

### ISSUE THREAD

**Issue by RCFilm** [djaydev/docker-recordings-transcoder#1]
When encoding sports DVR recordings the metadata is lost in the conversion. it seems plex saves the metadata of the sports game (i.e. NFL) in a separate file or SQL location. Could we please find a way to resolve this. An NFL game takes up about 10-16 GB in .ts, MPEG. and HDHomerun is a very poor encoder so pre-encoding is a no go. I use nvidia-subtitles.sh method of your system for HEVC.

**Comment by RCFilm** [comment]
One possible option is to add a variable to the docker template and script for the output file extension to be set to *.ts regardless of the real extension. Apparently, this method works with Plex just fine in order to keep the meta-data information. It would be a short-term fix and could be just a checkmark so you don't have to use it or would only be used in certain folders. 

"To fix the data not staying with the file... All you have to do is make sure you don't change the file name or extension. My file names preserve the .ts extension but are MKVs under the hood. Plex correctly detects its an MKV regardless of the file extension. https://imgur.com/a/huxSI
edit: Forgot to mention that I set this script as the post process script in the DVR settings."

https://www.reddit.com/r/PleX/comments/7xyy6t/transcode_dvr_recordings_to_x265_after_the_fact/

**Comment by djaydev** [comment]
@RCFilm Thanks for bringing this up, fixing this issue would make the whole system better overall.

I too experienced this very recently with sports from ESPN. It doesn't show any information about the recording after converting it. Just making sure this is what you mean correct?
![Capture](https://user-images.githubusercontent.com/33335484/65901061-610e6680-e385-11e9-9481-903bb580777c.PNG)

I believe it has something to do with the file name as you mentioned, once it gets changed to .mp4 instead of .ts the information it saved from the recording doesn't get applied to .mp4 file.

I have to think about a short term fix that doesn't cause more issues.  If the video gets converted but the name stays as "video.ts" the watcher will grab the video and try to convert it again.  It doesn't just look at the file name but the size as well and creates a hash number.  After conversion, the video is much smaller so it will have a new hash.  

My first thought is creating an option for saving the new video to .ts, creating the new hash of the newly converted video, logging the new video as "successfully converted" so that the new video will be ignored by the watcher.  This will cause two entries in the "successful_conversions" file per recording but I guess that's not a bid deal. 

I'll let you know what I come up with.

**Comment by RCFilm** [comment]
Thank you,

Notes.
A hash would work well but may add extra time to the processing (not much ;)). One method I used in the past was to simply keep a running log of all successful or failed encodes completed to the log in the current working Dir or in the config dir. Another place is to add metadata in the mkv or mp4 file to indicate successfully competed or failed encodes then use a prescan with [MediaInfo](https://mediaarea.net/en/MediaInfo) to scan the metadata.

**Comment by djaydev** [comment]
Sorry, what I meant was it currently uses hashes (as of today) to keep track of which file has been converted already and to skip that exact file if so.  It writes the file name and a hash number to a file called "successful_conversions" after converting the video.ts file.  

Because of that, if we convert the video and the newly converted file has the same name but now a different hash number, it will convert it again.  It would have to be moved to another folder outside of /watch folder.  Again that's currently though, if I can figure out the second hash logging idea, then it will skip it that way, but also cause two entries in the "successful_conversions" file per recording.

I looked at your github profile just now are you a developer?  If you can provide any coding/dev expertise to make this better that would be awesome!  I'm not a developer I just copy/pasted all this stuff in the repo from other repos. Most of it I don't even know what it does or why.

**Comment by RCFilm** [comment]
Honestly I have not coded much mostly just scripted other code. I was a Linux sysAdmin, but now I returned to school to get a BS in CS for software engineering. I have only just fulfilled my prerequisites so am just starting my CS courses this term. 
In short, I can read most code and edit completed code to suit my needs but creating my own is a struggle. Although, i am getting better. 


That said. I will look at it. But since you currently have a hash check for "successful_conversions" I don’t seen why you can just it and skip all in log. In the future you can use mediainfo to scan the files instead. This gives you the ability to se how the file is actually wrapped (ext) and encoded (codec).

Then if you run mediainfo on all files in the watch folder and sees it’s still mpegt Or any and/or has a .ts or any wrapper format then convert to ***. You can then also tell ffmepg to simply perform a “ -codec copy ” instead of full encode to save time of the file is already encoded but just requires a new wrapper (ext)

**Comment by djaydev** [comment]
> 
> That said. I will look at it. But since you currently have a hash check for "successful_conversions" I don’t see why you can just skip all in files log.
Currently the only file that's logged in the "successful_conversions" is the old video file, currently the new file is always a .mp4 so that's automatically ignored. 
> 
> In the future you can use mediainfo to scan the files instead. This gives you the ability to se how the file is actually wrapped (ext) and encoded (codec).
> 
> Then if you run mediainfo on all files in the watch folder and sees it’s still mpegt Or any and/or has a .ts or any wrapper format then convert to ***. You can then also tell ffmepg to simply perform a “ -codec copy ” instead of full encode to save time of the file is already encoded but just requires a new wrapper (ext)

I'm not sure what you mean by using mediainfo in that fashion but I'm open to anything.  If you can send me to script lines to include I'll test and try to get it working.

**Comment by djaydev** [comment]
Hi @RCFilm still a work in progress but hopefully I can get something going.

I'll save the long explanation but the short of it is the only way I can see this working at all is to convert the video codec but leave the video container as TS.  Like we said before it'll be an optional setting in the unraid template.

**Comment by RCFilm** [comment]
> Hi @RCFilm still a work in progress but hopefully I can get something going.
> 
> I'll save the long explanation but the short of it is the only way I can see this working at all is to convert the video codec but leave the video container as TS. Like we said before it'll be an optional setting in the unraid template.

That sounds great. I hope it's up in soon. I want to turn the app back on. 👍 

>I'm not sure what you mean by using mediainfo in that fashion but I'm open to anything. If you can send me some script lines to include I'll test and try to get it working.

I will see what I can send ya. I have been super busy with my 8-month-old son and school, but I will try.

**Comment by RCFilm** [comment]
Here is an example of what mediafile exports for a video file.

https://gist.githubusercontent.com/RCFilm/3348c91b76d1bf32ac7d10d054790a5f/raw/ed41a35e67b9444fa93939563a533d41abf41e2a/mediainfo_example

**Comment by djaydev** [comment]
wow that's a lot of info Mediainfo provides. Could be useful in some of my future projects.

>
>Basically the script uses mediainfo in this code to extract the videos dimensions, although mediainfo can extract basically any metadata information from the video as well.
>
That's in python. I'm so jealous you can read that it all looks like Arabic to me.

I'm looking over your previous messages about using mediainfo but I'm just not getting it.  This system is written all in bash if you or someone you know can give some example bash script lines to add to the current script I will add it, build it, and test it out.  

I've been doing a bunch of trial and error edits the last couple days and I keep hitting different road blocks.  It's mainly with how Plex manages the metadata for recordings.  If it's a recording that has metadata online in TVDB or similar it will download it from there, but metadata from the guide is finicky. The only thing that works so far is not doing anything with the recording file, which of course makes this system worthless.  The end result of this issue may be to use a different program other than this one for recordings that aren't listed online.

**Comment by djaydev** [comment]
Sorry for the spam last message

I searched github for someone else's code to try and copy and fix this issue. I ended up finding https://github.com/HaveAGitGat/Tdarr . It does what my docker does but a lot more!  It is made in javascript so I couldn't borrow any code but I'm just mentioning it in case you wanted to give it a try. Seems like it's made by a real developer unlike myself. 

 Sorry I couldn't help.

**Comment by djaydev** [comment]
Sorry old issue...

Plex is working on this issue, its available in the Plex beta update.

Plex Media Server 1.18.2.2029 is now available in the Beta update channel
FIXES:
    (DVR) Preserve EPG metadata when assimilating Sports and News recordings. (#10544)
    (Playlists) Recently added playlists were not sorted correctly
