### ISSUE TITLE
Getting No Conversion

### ISSUE THREAD

**Issue by TulsaStageHand** [djaydev/docker-recordings-transcoder#2]
/run/s6/services/autovideoconverter/autovideoconverter: line 250: basename: unbound variable

This is the error in the logs

**Comment by djaydev** [comment]
@TulsaStageHand sorry for the issue.  Are there any other log messages before the one you provided?

**Comment by djaydev** [comment]
@TulsaStageHand Send the complete docker log can I'll help with the issue.  To get the complete docker log you can use the CLI of the host and run "docker logs recordings-converter" or whatever name you gave the container.

**Comment by djaydev** [comment]
@TulsaStageHand 

Sorry for the late response, didn't get the email notification that you replied here.

I believe the issue is this part of the log "cannot create directory '/output':"  it's needs that directory "output" for the conversion process.  Can you provide the complete docker run command with all the variables and volumes please? thx

**Comment by TulsaStageHand** [comment]
kinda new to this, how to I get to that?

**Comment by djaydev** [comment]
No problem sorry about that.

If you start this container from the command line, it's typically done beginning with the command "docker run ... " followed by volumes, variables, flags, etc.  

If not from the command line, however you're starting the container, whether a GUI or docker compose or something else, I just need all the information you added to the container before you started it.  If it's a GUI, a screenshot will work fine.  For text based like docker compose, copy paste, text file attachment or whatever works best for you.

**Comment by TulsaStageHand** [comment]
I am using UnRaid and here is a screenshot of the docker file

**Comment by djaydev** [comment]
Ah Unraid cool, I use Unraid as well.  This container can run on any linux computer so I didn't want to assume.

I can't see the screenshot of the settings because you used email reply.  To attach an file you have to click the link to go to the github page and upload it there.

**Comment by TulsaStageHand** [comment]
![Image 6-3-20 at 10 35 AM](https://user-images.githubusercontent.com/66091182/83657894-1a61b380-a587-11ea-8d50-19b18692487e.jpg)

**Comment by djaydev** [comment]
Thanks.

Everything looks good, but let's try to change the user ID from "99" to "1000" and let me know if that helps.

**Comment by TulsaStageHand** [comment]
ok ill try that

**Comment by TulsaStageHand** [comment]
Still getting the same error with that change

**Comment by djaydev** [comment]
Ok was worth a shot. 

 I've since updated the docker to include /output folder at build time to avoid an possible errors about the /output folder at startup.  From the Unraid dashboard, click the icon for the docker to force an update, after it updates and starts up again send the log again so we can see what we get. thx

**Comment by TulsaStageHand** [comment]
ok

**Comment by TulsaStageHand** [comment]
data pulled 0kb

**Comment by TulsaStageHand** [comment]
something in line 250 in autovideoconverter   its saying unbound variable

**Comment by TulsaStageHand** [comment]
i have to run some errands and will be back later this afternoon

**Comment by djaydev** [comment]
We're almost there! One step at a time.

It's not the same issue, before it was /output.  

Now a new log message "/var/run/s6/etc/cont-init.d/02-setvariables.sh: line 19: [: =: unary operator expected"

Line 19 is subtitles.  Going back to your settings screenshot, you haven't said yes or no to subtitles.  Please use 1 for yes, 0 for no. thanks

**Comment by TulsaStageHand** [comment]
<img width="2560" alt="Screen Shot 2020-06-03 at 1 46 47 PM" src="https://user-images.githubusercontent.com/66091182/83676956-15a9f900-a5a1-11ea-8d09-258f8ded1ac7.png">
<img width="2560" alt="Screen Shot 2020-06-03 at 1 47 44 PM" src="https://user-images.githubusercontent.com/66091182/83676963-1773bc80-a5a1-11ea-86f3-2db62c4ca95f.png">

**Comment by djaydev** [comment]
Thank you for the screenshots, they definitely help.

I setup a test docker to see if a video with the same file name would work on my test system.  I discovered that because the file name has an apostrophe in the word "I'm" and linux doesn't like it.  Please try remove the apostrophe and change I'm to Im then run the container again.

**Comment by TulsaStageHand** [comment]
Looks like that was it. Its converting that file now.  I guess I will have to check the logs and see which files it doesn't like and change them so it will eventually convert them.  I will let you know if it is a successful conversion.

**Comment by TulsaStageHand** [comment]
Failed 


![Screen Shot 2020-06-03 at 4 21 11 PM](https://user-images.githubusercontent.com/66091182/83690472-709a1b00-a5b6-11ea-99f9-f32c2701006a.jpg)

**Comment by djaydev** [comment]
alright, still getting there step by step! I don't want to give up!

Phase 1 the program finding the video and starting the conversion script (basic summary).  That was the first issue and we're finally pass that.

Phase 2 is the conversion script itself, this is were we are now.

In order to look into this current issue more, I need a different log.  They are located in "/mnt/user/appdata/recordings-converter/log" and the files are called postProcess.(date/time).log.  Please attach those here, they will tell us what is causing the conversion to fail.

**Comment by TulsaStageHand** [comment]
[postProcess.03-06-2020-1534.log](https://github.com/djaydev/docker-recordings-transcoder/files/4731318/postProcess.03-06-2020-1534.log)

**Comment by TulsaStageHand** [comment]
it processed a lot of files and failed on a few.

[Logs.zip](https://github.com/djaydev/docker-recordings-transcoder/files/4731381/Logs.zip)

**Comment by djaydev** [comment]
I would need more time to match up the failed with the individual logs, but it looks like the majority were successful.  Please verify by checking your tv shows folder and looking for files that were once .ts files and should now be .mp4 files.

You can open the files "successful_conversions" and "failed_conversions" in a text editor to view exactly which files couldn't be converter.

**Comment by djaydev** [comment]
were you able to inspect the tv shows files that were once .ts files and should now be .mp4 files? Please play them and make sure they are watchable, audio sync'd, etc.  Also, after the initial batch of files, did any others fail? thx

**Comment by TulsaStageHand** [comment]
It looks like they all converted except the ones listed in the failed file I sent you, no others have shown up. I did a search for ts files and none are listed in my directories (except the failed files)  I played a few random ones that converted and all looks sync'd up and playing as they should. 

R

**Comment by djaydev** [comment]
Great news!
From what I can tell, the 6 in the failed_conversions file were all because of special characters in the name, 5 of them have a "&" and the 6th has an apostrophe.  I'm trying to figure out a way to force it to work with those characters or convert the names for you on the output file.  Once I figure it out you'll automatically receive it on the next docker update.

**Comment by inenting** [comment]
Hey, just wanted to ask if you managed to fix this/ignore this problem yet, I have the same problem with files which have japanese/korean/russian characters in them. Unfortunately it just gets stuck on that file and doesn't move on. I have thousands of files which probably have unknown characters so renaming them manually isn't an option

**Comment by djaydev** [comment]
I believe this issue has something to do with locales but unfortunately I'm not quite sure how to fix it. Try adding the following docker variable to the docker container and let me know if it works.

`-e LANG=C.UTF-8`

**Comment by inenting** [comment]
Hey Sorry for my late reply, unfortunately that didn't work. Is there maybe a way to skip files with illegal characters in them because it just gets stuck on the first one and keeps looping?

**Comment by djaydev** [comment]
There is a mechanism to skip failed files.  How that works is the script saves the filename of the failed video to a list, and skips any video saved in said list.  Unfortunately, the issue with the invalid characters is the file name becomes blank, so it can't save it to the list for skipping, and this is why it keeps looping.  

I don't have any special characters recordings to test and I'm not sure how to work with them in Linux bash scripts.  If you or someone you know can contribute to the project to help with this issue I will add it to the project.  

Sorry I can't help.

**Comment by inenting** [comment]
Is there a possibility we can change that mechanism to save a (easy/small) hash of the file to the list and use that instead of names? I'm not a programmer so I can't help unfortunately, if there is another way I can help, hit me up.

**Comment by djaydev** [comment]
The script does just that, it logs the filename and a hash, but unfortunately the process that creates the hash needs a filename.  Since your files have invalid characters it shows as <blank>.  So in your case the script says "hey create a hash for file <NOTHING>".   Hope that makes sense.

**Comment by djaydev** [comment]
closure: two weeks no community response to help wanted
